server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

spring:
  kafka:
    bootstrap-servers: localhost:29092    # 도커 외부 포트(네 compose에서 29092 매핑)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: reward-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.kafka.demo"
        spring.json.value.default.type: com.kafka.demo.ShareCreatedEvent
      auto-offset-reset: earliest
logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.kafka.listener: INFO

app:
  topics:
    share-created: share-created.v1
    reward-granted: reward.granted.v1


